using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;
using Ara3D.DataFlowEngine;
using Ara3D.DataFlowEngine.Abstractions;
using Ara3D.DataFlowEngine.TestKit;
using Ara3D.DataTable;
using Ara3D.NodeGraph;
using BimOpenFlow.Host;
using BimOpenFlow.TestSupport;

namespace BimOpenFlow.TableWorkflows.Tests;

/// <summary>One graph of samples/buildings/index.json: its id, the bim-open-data sample it
/// reads (a name in samples/public/samples.json), and the question it answers.</summary>
public sealed record BuildingGraph(string Id, string Building, string Question);

/// <summary>
/// The sample graphs over public buildings (samples/buildings) and the data they read,
/// bim-open-data's samples/public, reached through deps/ after `node deps.mjs`. The graphs
/// name the data folder with a placeholder that index.json declares, so they hold no
/// machine-local path. SiteJson evaluates every graph and writes what the landing page
/// (site/data/buildings.json) shows: each graph, and a sample of every node's table.
/// </summary>
public static class PublicBuildings
{
    /// <summary>Rows of each node's table the page shows; the full row count is kept beside them.</summary>
    public const int SampleRows = 20;

    public static string GraphsDir => RepoPaths.Samples("buildings");

    public static string SiteDataFile => Path.Combine(RepoPaths.Root, "site", "data", "buildings.json");

    /// <summary>bim-open-data's notice for the sample buildings, which ships with every page
    /// that shows results derived from them, copied beside the results.</summary>
    public static string SiteNoticeFile => Path.Combine(RepoPaths.Root, "site", "data", "NOTICE.md");

    public static string NoticeFile => Path.Combine(DataDir, "NOTICE.md");

    private static JsonObject Index { get; } =
        JsonNode.Parse(File.ReadAllText(Path.Combine(GraphsDir, "index.json")))!.AsObject();

    public static string Placeholder => (string)Index["placeholder"]!;

    public static string DataDir => Path.GetFullPath(Path.Combine(RepoPaths.Root, (string)Index["data"]!));

    public static IReadOnlyList<BuildingGraph> Graphs { get; } = Index["graphs"]!.AsArray()
        .Select(g => new BuildingGraph((string)g!["id"]!, (string)g["building"]!, (string)g["question"]!))
        .ToList();

    /// <summary>Null when the data is present, else why the tests skip.</summary>
    public static string? MissingDataReason
        => File.Exists(Path.Combine(DataDir, "samples.json"))
            ? null
            : $"Public sample buildings not found at {DataDir}. Run `node deps.mjs` (bim-open-data pinned at a commit with samples/public).";

    public static string GraphFile(string id)
        => Path.Combine(GraphsDir, id + ".json");

    public static GraphDocument Load(string id)
        => SampleSeeding.RewritePaths(GraphDocumentIO.Load(GraphFile(id)), Placeholder, DataDir);

    public static FlowTestSession Evaluate(string id)
    {
        var session = TableReads.NewTableSession();
        session.Evaluate(Load(id));
        return session;
    }

    /// <summary>The landing page's data: for each graph, its document as committed, the
    /// question, the building's title from samples.json, and per node its status and, for a
    /// node with a table output, the row count, columns, and the first SampleRows rows.</summary>
    public static string SiteJson()
    {
        var samples = JsonNode.Parse(File.ReadAllText(Path.Combine(DataDir, "samples.json")))!["samples"]!.AsArray();
        string Title(string name) => (string)samples.Single(s => (string)s!["name"]! == name)!["title"]!;
        var graphs = new JsonArray();
        foreach (var graph in Graphs)
        {
            var session = Evaluate(graph.Id);
            var nodes = new JsonObject();
            foreach (var (nodeId, result) in session.Snapshot.Results.OrderBy(r => r.Key, StringComparer.Ordinal))
                nodes[nodeId] = NodeJson(session, nodeId, result);
            graphs.Add(new JsonObject
            {
                ["id"] = graph.Id,
                ["building"] = graph.Building,
                ["buildingTitle"] = Title(graph.Building),
                ["question"] = graph.Question,
                ["document"] = JsonNode.Parse(File.ReadAllText(GraphFile(graph.Id))),
                ["nodes"] = nodes,
            });
        }
        var root = new JsonObject
        {
            ["about"] = "Generated by PublicBuildingsSiteData.Write in tests/flow/BimOpenFlow.TableWorkflows.Tests from samples/buildings over bim-open-data's samples/public. Do not edit by hand.",
            ["sampleRows"] = SampleRows,
            ["graphs"] = graphs,
        };
        return root.ToJsonString(new JsonSerializerOptions { WriteIndented = true }).Replace("\r\n", "\n") + "\n";
    }

    private static JsonObject NodeJson(FlowTestSession session, string nodeId, NodeResult result)
    {
        var node = new JsonObject { ["status"] = result.Status.ToString() };
        if (result.Error is { } error)
            node["error"] = error;
        if (result.Status == NodeStatus.Ok && TableOutput(session, nodeId) is { } table)
        {
            node["rowCount"] = table.Rows.Count;
            node["columns"] = new JsonArray(table.Columns
                .Select(c => (JsonNode)new JsonObject { ["name"] = c.Descriptor.Name, ["type"] = c.Descriptor.Type.Name })
                .ToArray());
            node["rows"] = new JsonArray(Enumerable.Range(0, Math.Min(SampleRows, table.Rows.Count))
                .Select(r => (JsonNode)new JsonArray(table.Columns.Select(c => Cell(table[c.ColumnIndex, r])).ToArray()))
                .ToArray());
        }
        return node;
    }

    private static IDataTable? TableOutput(FlowTestSession session, string nodeId)
    {
        try
        {
            return session.Output(nodeId, "table") is TableValue value ? value.Table : null;
        }
        catch (FlowAssertionException)
        {
            return null;
        }
    }

    private static JsonNode? Cell(object? value) => value switch
    {
        null or DBNull => null,
        string s => JsonValue.Create(s),
        bool b => JsonValue.Create(b),
        int or long or short or byte or uint or ulong => JsonValue.Create(Convert.ToInt64(value, CultureInfo.InvariantCulture)),
        double or float or decimal => JsonValue.Create(Convert.ToDouble(value, CultureInfo.InvariantCulture)),
        _ => JsonValue.Create(Convert.ToString(value, CultureInfo.InvariantCulture)),
    };
}
